"""
Experiment S2: Spatial XGBoost Training & Evaluation (Wind-Aware).

Trains three XGBoost models (6h / 24h / 72h) that augment the locked canonical
feature sets with 3 concurrent wind-aware spatial neighbour features generated by
backend/ml/spatial_features.py.

Rules:
- NEVER overwrites xgb_weather_pm25_{h}_tuned.joblib (champion models).
- Uses the LOCKED hyperparameters from backend/ml/results/xgb_best_params.json.
- Uses the LOCKED canonical feature lists from backend/models/horizon_features.json.
- Spatial features are appended AFTER canonical features.
- Saves experimental models as:
      backend/models/xgb_spatial_s2_pm25_6h_experimental.joblib
      backend/models/xgb_spatial_s2_pm25_24h_experimental.joblib
      backend/models/xgb_spatial_s2_pm25_72h_experimental.joblib
- Writes a full results report to:
      backend/ml/results/spatial_s2_evaluation.json

Temporal split (matches champion training):
  Train : all timestamps < 2024-01-01
  Test  : all timestamps >= 2024-01-01

Evaluation output (per horizon):
  Overall   : MAE, RMSE, R², Bias, MedAE
  By regime : Good / Moderate / Unhealthy / Very Unhealthy / Hazardous
  By station: MAE for each of the 10 Delhi stations
  Improvement: S2 vs S0 champion delta (%) for MAE and RMSE
"""

from __future__ import annotations

import json
import logging
import sys
import warnings
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor

warnings.filterwarnings("ignore", category=UserWarning)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_FILE = BASE_DIR / "data" / "processed" / "delhi_forecasting_weather.csv"
METADATA_FILE = BASE_DIR / "data" / "metadata" / "delhi_station_coordinates.csv"
HORIZON_FEATURES_FILE = BASE_DIR / "models" / "horizon_features.json"
XGB_PARAMS_FILE = BASE_DIR / "ml" / "results" / "xgb_best_params.json"
MODELS_DIR = BASE_DIR / "models"
RESULTS_DIR = BASE_DIR / "ml" / "results"

HORIZONS = ["6h", "24h", "72h"]
TARGET_COLS = {
    "6h": "target_pm25_6h",
    "24h": "target_pm25_24h",
    "72h": "target_pm25_72h",
}

# Experimental model filenames — NEVER the same as champion model names.
EXPERIMENTAL_MODEL_NAMES = {
    "6h": "xgb_spatial_s2_pm25_6h_experimental.joblib",
    "24h": "xgb_spatial_s2_pm25_24h_experimental.joblib",
    "72h": "xgb_spatial_s2_pm25_72h_experimental.joblib",
}

# Champion S0 validation metrics from xgb_best_params.json (reference baseline)
S0_CHAMPION_METRICS: dict[str, dict] = {}  # filled after loading params file

TRAIN_CUTOFF = "2024-01-01"

# AQI PM2.5 breakpoints (µg/m³) for regime analysis
REGIME_BINS = [0, 30, 60, 90, 120, np.inf]
REGIME_LABELS = ["Good", "Moderate", "Unhealthy", "Very Unhealthy", "Hazardous"]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def load_config() -> tuple[dict, dict]:
    """Load horizon feature lists and locked XGBoost hyperparameters."""
    with open(HORIZON_FEATURES_FILE) as f:
        horizon_cfg = json.load(f)
    with open(XGB_PARAMS_FILE) as f:
        xgb_params = json.load(f)
    return horizon_cfg, xgb_params


def medae(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.median(np.abs(y_true - y_pred)))


def compute_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    mae = float(mean_absolute_error(y_true, y_pred))
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    r2 = float(r2_score(y_true, y_pred))
    bias = float(np.mean(y_pred - y_true))
    med = medae(y_true, y_pred)
    return {"MAE": mae, "RMSE": rmse, "R2": r2, "Bias": bias, "MedAE": med}


def compute_regime_metrics(
    y_true: np.ndarray, y_pred: np.ndarray, labels: list[str]
) -> dict:
    """Compute per-AQI-regime MAE."""
    out = {}
    for label, lo, hi in zip(
        labels, REGIME_BINS[:-1], REGIME_BINS[1:]
    ):
        mask = (y_true >= lo) & (y_true < hi)
        if mask.sum() >= 5:
            out[label] = {
                "n_samples": int(mask.sum()),
                "MAE": float(mean_absolute_error(y_true[mask], y_pred[mask])),
                "RMSE": float(np.sqrt(mean_squared_error(y_true[mask], y_pred[mask]))),
            }
        else:
            out[label] = {"n_samples": int(mask.sum()), "MAE": None, "RMSE": None}
    return out


def compute_station_metrics(
    df_test: pd.DataFrame, y_pred: np.ndarray, target_col: str
) -> dict:
    """Compute per-station MAE on the test set."""
    df = df_test.copy()
    df["_pred"] = y_pred
    out = {}
    for station, grp in df.groupby("station_id"):
        valid = grp[target_col].notna() & grp["_pred"].notna()
        n = int(valid.sum())
        if n >= 5:
            out[str(station)] = {
                "n_samples": n,
                "MAE": float(mean_absolute_error(grp.loc[valid, target_col], grp.loc[valid, "_pred"])),
            }
        else:
            out[str(station)] = {"n_samples": n, "MAE": None}
    return out


def improvement_pct(s0_val: float, s1_val: float) -> float:
    """Positive → S2 better (lower error). Negative → S2 worse."""
    if s0_val == 0:
        return 0.0
    return float((s0_val - s1_val) / s0_val * 100.0)


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------
def main() -> None:
    logger.info("=" * 68)
    logger.info("VAYUNET  |  Experiment S2: Wind-Aware Spatial XGBoost")
    logger.info("=" * 68)

    # ------------------------------------------------------------------
    # Safety check: ensure experimental models won't clobber champions
    # ------------------------------------------------------------------
    for h, exp_name in EXPERIMENTAL_MODEL_NAMES.items():
        champion_name = f"xgb_weather_pm25_{h}_tuned.joblib"
        assert exp_name != champion_name, (
            f"ABORT: experimental model name collides with champion: {exp_name}"
        )
    logger.info("Safety check passed — experimental models will not overwrite champions.")

    # ------------------------------------------------------------------
    # Load config
    # ------------------------------------------------------------------
    horizon_cfg, xgb_params_cfg = load_config()
    horizon_features: dict[str, list[str]] = horizon_cfg["horizon_features"]
    feature_counts: dict[str, int] = horizon_cfg["feature_counts"]

    logger.info("Canonical feature counts loaded from horizon_features.json:")
    for h in HORIZONS:
        logger.info(f"  {h:>4s}: {feature_counts[h]} canonical features")

    # ------------------------------------------------------------------
    # Load data
    # ------------------------------------------------------------------
    logger.info(f"Loading dataset: {DATA_FILE.name}")
    df = pd.read_csv(DATA_FILE, parse_dates=["timestamp"])
    logger.info(f"  Raw dataset: {len(df):,} rows × {len(df.columns)} columns")

    # ------------------------------------------------------------------
    # Add spatial features (S2)
    # ------------------------------------------------------------------
    logger.info("Computing S2 spatial features...")
    sys.path.insert(0, str(BASE_DIR))
    from ml.spatial_features import (
        add_spatial_features,
        get_spatial_feature_names,
        load_station_coordinates,
    )

    coords_df = load_station_coordinates(METADATA_FILE)
    df = add_spatial_features(df, coords_df)
    spatial_cols = get_spatial_feature_names()
    logger.info(f"  Spatial features added: {spatial_cols}")
    logger.info(f"  Dataset after augmentation: {len(df):,} rows × {len(df.columns)} columns")

    # ------------------------------------------------------------------
    # One-hot encode station_id
    # ------------------------------------------------------------------
    logger.info("One-hot encoding station_id...")
    expected_stations = [
        "anand vihar", "aya nagar", "bawana", "ito", "jahangirpuri",
        "narela", "punjabi bagh", "r k puram", "vivek vihar", "wazirpur",
    ]
    station_dummies = pd.get_dummies(df["station_id"], prefix="station_id")
    # Ensure all 10 station columns are present
    for stn in expected_stations:
        col = f"station_id_{stn}"
        if col not in station_dummies.columns:
            station_dummies[col] = 0
    df = pd.concat([df, station_dummies], axis=1)
    logger.info(f"  Station dummy columns added: {sorted(station_dummies.columns.tolist())}")

    # ------------------------------------------------------------------
    # Temporal split
    # ------------------------------------------------------------------
    train_mask = df["timestamp"] < TRAIN_CUTOFF
    test_mask = df["timestamp"] >= TRAIN_CUTOFF
    df_train = df[train_mask].copy()
    df_test = df[test_mask].copy()
    logger.info(
        f"Temporal split — Train: {len(df_train):,} rows  |  Test: {len(df_test):,} rows  "
        f"(cutoff: {TRAIN_CUTOFF})"
    )

    # ------------------------------------------------------------------
    # Per-horizon training and evaluation
    # ------------------------------------------------------------------
    all_results: dict = {"experiment": "S2_spatial_wind_aware", "horizons": {}}

    for h in HORIZONS:
        logger.info("")
        logger.info(f"{'─'*68}")
        logger.info(f"  Horizon: {h}")
        logger.info(f"{'─'*68}")

        target_col = TARGET_COLS[h]
        canonical_feats = horizon_features[h]
        s2_feats = canonical_feats + spatial_cols

        logger.info(
            f"  Features: {len(canonical_feats)} canonical + {len(spatial_cols)} spatial "
            f"= {len(s2_feats)} total"
        )

        # Validate all features exist
        missing = [c for c in s2_feats if c not in df.columns]
        if missing:
            logger.error(f"  [ABORT] Missing columns for {h}: {missing}")
            sys.exit(1)

        # Train / test slices
        valid_train = df_train[target_col].notna()
        valid_test = df_test[target_col].notna()

        X_train = df_train.loc[valid_train, s2_feats].values
        y_train = df_train.loc[valid_train, target_col].values
        X_test = df_test.loc[valid_test, s2_feats].values
        y_test = df_test.loc[valid_test, target_col].values

        logger.info(
            f"  Train samples: {len(X_train):,}  |  Test samples: {len(X_test):,}"
        )

        # Locked hyperparameters
        params = xgb_params_cfg[h]["params"]
        best_iteration = xgb_params_cfg[h]["best_iteration"]

        logger.info(f"  Locked params: {params}")
        logger.info(f"  n_estimators (from best_iteration): {best_iteration}")

        model = XGBRegressor(
            n_estimators=best_iteration,
            objective="reg:squarederror",
            tree_method="hist",
            random_state=42,
            n_jobs=-1,
            verbosity=0,
            **params,
        )

        logger.info("  Training...")
        model.fit(X_train, y_train)
        logger.info("  Training complete.")

        # ------------------------------------------------------------------
        # Evaluation
        # ------------------------------------------------------------------
        y_pred = model.predict(X_test)

        overall = compute_metrics(y_test, y_pred)
        logger.info(
            f"  Overall  →  MAE={overall['MAE']:.3f}  RMSE={overall['RMSE']:.3f}  "
            f"R²={overall['R2']:.4f}  Bias={overall['Bias']:.3f}  MedAE={overall['MedAE']:.3f}"
        )

        # S0 champion baseline (from xgb_best_params.json validation metrics)
        s0_metrics = xgb_params_cfg[h].get("validation_metrics", {})
        delta_mae = improvement_pct(s0_metrics.get("MAE", 0), overall["MAE"])
        delta_rmse = improvement_pct(s0_metrics.get("RMSE", 0), overall["RMSE"])
        logger.info(
            f"  vs S0    →  ΔMAE={delta_mae:+.2f}%  ΔRMSE={delta_rmse:+.2f}%  "
            f"(positive = S2 better)"
        )

        # Regime breakdown
        regime_metrics = compute_regime_metrics(y_test, y_pred, REGIME_LABELS)
        logger.info("  Regime breakdown (MAE):")
        for regime, rm in regime_metrics.items():
            n = rm["n_samples"]
            mae_str = f"{rm['MAE']:.2f}" if rm["MAE"] is not None else "n/a"
            logger.info(f"    {regime:<16}: n={n:>6,}  MAE={mae_str}")

        # Station-level MAE
        df_test_valid = df_test[valid_test].copy()
        station_metrics = compute_station_metrics(df_test_valid, y_pred, target_col)
        logger.info("  Station-level MAE:")
        for stn, sm in sorted(station_metrics.items()):
            mae_str = f"{sm['MAE']:.2f}" if sm["MAE"] is not None else "n/a"
            logger.info(f"    {stn:<18}: n={sm['n_samples']:>5,}  MAE={mae_str}")

        # ------------------------------------------------------------------
        # Save experimental model
        # ------------------------------------------------------------------
        model_path = MODELS_DIR / EXPERIMENTAL_MODEL_NAMES[h]
        joblib.dump(model, model_path)
        logger.info(f"  Saved experimental model → {model_path.relative_to(BASE_DIR)}")

        # Confirm champion was NOT touched
        champion_path = MODELS_DIR / f"xgb_weather_pm25_{h}_tuned.joblib"
        assert champion_path.exists(), f"Champion model missing: {champion_path}"

        # ------------------------------------------------------------------
        # Collect results
        # ------------------------------------------------------------------
        all_results["horizons"][h] = {
            "feature_count_canonical": len(canonical_feats),
            "feature_count_spatial": len(spatial_cols),
            "feature_count_total": len(s2_feats),
            "train_samples": int(len(X_train)),
            "test_samples": int(len(X_test)),
            "overall_metrics": overall,
            "s0_champion_metrics": s0_metrics,
            "improvement_vs_s0": {
                "delta_mae_pct": round(delta_mae, 4),
                "delta_rmse_pct": round(delta_rmse, 4),
                "interpretation": (
                    "S2_BETTER" if delta_mae >= 0 else "S2_WORSE"
                ),
            },
            "regime_metrics": regime_metrics,
            "station_metrics": station_metrics,
            "model_saved": str(model_path.relative_to(BASE_DIR)),
        }

    # ------------------------------------------------------------------
    # Write results JSON
    # ------------------------------------------------------------------
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    results_path = RESULTS_DIR / "spatial_s2_evaluation.json"
    with open(results_path, "w") as f:
        json.dump(all_results, f, indent=2, default=str)
    logger.info("")
    logger.info(f"Results written → {results_path.relative_to(BASE_DIR)}")

    # ------------------------------------------------------------------
    # Summary table
    # ------------------------------------------------------------------
    logger.info("")
    logger.info("=" * 68)
    logger.info("EXPERIMENT S2 SUMMARY")
    logger.info("=" * 68)
    logger.info(
        f"{'Horizon':<8} {'S0 MAE':>9} {'S2 MAE':>9} {'ΔMAE%':>8} "
        f"{'S0 RMSE':>10} {'S2 RMSE':>10} {'ΔRMSE%':>9} {'Decision':>12}"
    )
    logger.info("─" * 80)
    for h in HORIZONS:
        hr = all_results["horizons"][h]
        s0m = hr["s0_champion_metrics"]
        s1m = hr["overall_metrics"]
        d = hr["improvement_vs_s0"]
        dm = d["delta_mae_pct"]
        dr = d["delta_rmse_pct"]
        flag = "🟢 BETTER" if dm >= 2.0 else ("🟡 MARGINAL" if dm >= 0.5 else "🔴 WORSE")
        logger.info(
            f"{h:<8} {s0m.get('MAE', 0):>9.3f} {s1m['MAE']:>9.3f} {dm:>+8.2f}% "
            f"{s0m.get('RMSE', 0):>10.3f} {s1m['RMSE']:>10.3f} {dr:>+9.2f}% "
            f"{flag:>12}"
        )
    logger.info("=" * 68)


if __name__ == "__main__":
    main()
